export const ROUTES_ID = {
    home: "home",
    contact: "contact",
    category: "category",
    login: "login",
    skep: "skep",
    favorite: "favorite",
    notfound: "notfound",
    register: "register",
    forgotpassword: "forgotpassword",
    private: "private",
    profile: "profile",
    payment: "payment",
    detail: "detail",
    updatepassword: "updatepassword",
    homeForm: "homeForm",
    myOrders: "myOrders",
    tshirt: "tshirt",
    short: "short",
    pant: "pant",
    bag: "bag",
    hat: "hat",
}